---
# Tasks for installing and configuring DNS Server on Ubuntu 20.04

- name: Make sure everything is up to date
  apt:
    name: "*"
    state: latest
- name: Install bind9
  apt:
    name: bind9
    state: present
- name: Install dnsutils and systemctl
  apt:
    name: [ "dnsutils" ]
    state: present
- name: Include hostconfig tasks
  include_tasks: "hostconfig.yml"
- name: Enable the bind9 service on restart
  systemd:
    name: bind9
    enabled: true
- name: Restart the bind9 service (apply config)
  systemd:
    name: bind9
    state: restarted
