---
# Tasks for templating and setting up host config

- name: Template named configrations
  copy:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "/etc/bind/{{ item }}"
    force: true
  with_items:
    - named.conf.local
    - named.conf.options
- name: Create directory for zone configuration
  file:
    path: /etc/bind/zones
    state: directory
    mode: "0755"
- name: Template zone configurations
  copy:
    src: "{{ role_path }}/templates/zone.config.j2"
    dest: "/etc/bind/zones/db.{{ domain_name }}"
    force: true
