name: test-ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Docker setup
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: stable
      - run: |
          ls -lR ../
          docker build -t ansible-dev-local:latest -f ./Dockerfile.test ./ && \
          docker run -t ansible-dev-local:latest
